# Generated by Django 4.2.7 on 2024-12-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_cliente_proveedor_usuario_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_caducidad', models.DateField()),
                ('cantidad_stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
