# Generated by Django 4.2.7 on 2025-01-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_venta_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='destinatario',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
