# Generated by Django 4.2.7 on 2025-01-08 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_venta_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
