# Generated by Django 4.2.7 on 2025-01-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('elemento', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('responsable', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='destinatario',
            field=models.CharField(default='', max_length=100),
        ),
    ]
