# Generated by Django 4.2.7 on 2025-01-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_date_auditlog_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='date_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='element_delivered',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='recipient',
        ),
    ]
