# Generated by Django 4.2.7 on 2025-01-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_date_time_auditlog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.TextField(),
        ),
    ]
